/**
 * Leads workflow plugin.
 *
 * Contributes the lead/CRM triggers, conditions and actions to the generic
 * registry. Every real entry's `id` matches the existing AutomationRule
 * vocabulary (AutomationTrigger / RuleConditionType / RuleActionType) so the
 * persisted rule JSON is unchanged.
 *
 * `comingSoon` entries are roadmap connectors: shown (in Enterprise mode) but
 * disabled and never persistable — purely to make the catalog's breadth and
 * the plugin architecture visible.
 */
import type { CatalogEntry, WorkflowPlugin } from "./registry";

const t = (e: Omit<CatalogEntry, "kind" | "plugin">): CatalogEntry => ({
  ...e,
  kind: "trigger",
  plugin: "leads",
});
const c = (e: Omit<CatalogEntry, "kind" | "plugin">): CatalogEntry => ({
  ...e,
  kind: "condition",
  plugin: "leads",
});
const a = (e: Omit<CatalogEntry, "kind" | "plugin">): CatalogEntry => ({
  ...e,
  kind: "action",
  plugin: "leads",
});

const triggers: CatalogEntry[] = [
  // Leads
  t({
    id: "LEAD_CREATED",
    label: "Lead erstellt",
    description: "Startet, sobald ein neuer Lead angelegt wird.",
    category: "Leads",
    icon: "userPlus",
    tone: "indigo",
    keywords: ["neu", "new", "anlegen", "eingang"],
    tier: "simple",
  }),
  t({
    id: "MANUAL",
    label: "Manuell / Test",
    description: "Wird nur manuell ausgelöst – ideal zum Testen.",
    category: "Leads",
    icon: "bolt",
    tone: "slate",
    keywords: ["test", "manuell", "hand"],
    tier: "simple",
  }),
  // Kommunikation
  t({
    id: "MESSAGE_INBOUND",
    label: "Antwort erhalten",
    description: "Der Lead hat auf WhatsApp oder E-Mail geantwortet.",
    category: "Kommunikation",
    icon: "reply",
    tone: "emerald",
    keywords: ["antwort", "reply", "inbound", "whatsapp", "eingehend"],
    tier: "simple",
  }),
  t({
    id: "MESSAGE_FAILED",
    label: "Nachricht fehlgeschlagen",
    description: "Eine ausgehende Nachricht konnte nicht zugestellt werden.",
    category: "Kommunikation",
    icon: "x",
    tone: "rose",
    keywords: ["fehler", "failed", "bounce", "zustellung"],
    tier: "pro",
  }),
  // Termine
  t({
    id: "APPOINTMENT_CREATED",
    label: "Termin erstellt",
    description: "Ein Termin wurde für den Lead angelegt.",
    category: "Termine",
    icon: "calendar",
    tone: "sky",
    keywords: ["termin", "appointment", "meeting", "kalender"],
    tier: "simple",
  }),
  t({
    id: "APPOINTMENT_MISSED",
    label: "Termin verpasst",
    description: "Der Lead ist nicht zum Termin erschienen (No-Show).",
    category: "Termine",
    icon: "calendarX",
    tone: "rose",
    keywords: ["no show", "verpasst", "missed", "nicht erschienen"],
    tier: "pro",
  }),
  // Dokumente
  t({
    id: "DOCUMENT_REQUESTED",
    label: "Dokument angefordert",
    description: "Es wurde ein Dokument vom Lead angefordert.",
    category: "Dokumente",
    icon: "doc",
    tone: "teal",
    keywords: ["dokument", "unterlagen", "angefordert", "request"],
    tier: "pro",
  }),
  t({
    id: "DOCUMENT_UPLOADED",
    label: "Dokument hochgeladen",
    description: "Der Lead hat ein Dokument hochgeladen.",
    category: "Dokumente",
    icon: "doc",
    tone: "teal",
    keywords: ["upload", "hochgeladen", "dokument"],
    tier: "simple",
  }),
  t({
    id: "DOCUMENT_APPROVED",
    label: "Dokument geprüft",
    description: "Ein hochgeladenes Dokument wurde geprüft/freigegeben.",
    category: "Dokumente",
    icon: "docCheck",
    tone: "teal",
    keywords: ["geprüft", "approved", "freigegeben", "dokument"],
    tier: "pro",
  }),
  // Vertrieb
  t({
    id: "LEAD_STATUS_CHANGED",
    label: "Status geändert",
    description: "Der Pipeline-Status des Leads hat sich geändert.",
    category: "Vertrieb",
    icon: "swap",
    tone: "blue",
    keywords: ["status", "pipeline", "stage", "phase"],
    tier: "simple",
  }),
  t({
    id: "LEAD_OWNER_ASSIGNED",
    label: "Bearbeiter geändert",
    description: "Dem Lead wurde ein (neuer) Bearbeiter zugewiesen.",
    category: "Vertrieb",
    icon: "userPlus",
    tone: "blue",
    keywords: ["bearbeiter", "owner", "zuweisung", "assignee"],
    tier: "pro",
  }),
  t({
    id: "TASK_OVERDUE",
    label: "Aufgabe überfällig",
    description: "Eine Aufgabe zum Lead ist überfällig.",
    category: "Vertrieb",
    icon: "clock",
    tone: "amber",
    keywords: ["aufgabe", "task", "überfällig", "overdue"],
    tier: "pro",
  }),
  t({
    id: "SLA_EXCEEDED",
    label: "SLA überschritten",
    description: "Eine Reaktionszeit-Vorgabe (SLA) wurde überschritten.",
    category: "Vertrieb",
    icon: "gauge",
    tone: "amber",
    keywords: ["sla", "reaktionszeit", "frist", "eskalation"],
    tier: "enterprise",
  }),
  // Roadmap connectors (visible in Enterprise, disabled)
  t({
    id: "roadmap.wa_delivered",
    label: "WhatsApp zugestellt",
    description: "Löst aus, sobald eine WhatsApp zugestellt wurde.",
    category: "Kommunikation",
    icon: "check2",
    tone: "emerald",
    keywords: ["whatsapp", "zugestellt", "delivered"],
    tier: "enterprise",
    comingSoon: true,
  }),
  t({
    id: "roadmap.wa_read",
    label: "WhatsApp gelesen",
    description: "Löst aus, sobald eine WhatsApp gelesen wurde.",
    category: "Kommunikation",
    icon: "check2",
    tone: "emerald",
    keywords: ["whatsapp", "gelesen", "read", "blaue haken"],
    tier: "enterprise",
    comingSoon: true,
  }),
  t({
    id: "roadmap.link_clicked",
    label: "Link geklickt",
    description: "Löst aus, sobald der Lead einen Link geklickt hat.",
    category: "Kommunikation",
    icon: "link",
    tone: "emerald",
    keywords: ["link", "klick", "click", "tracking"],
    tier: "enterprise",
    comingSoon: true,
  }),
];

const conditions: CatalogEntry[] = [
  c({
    id: "leadStatus",
    label: "Status ist",
    description: "Nur wenn der Lead einen bestimmten Status hat.",
    category: "Lead-Eigenschaften",
    icon: "swap",
    tone: "blue",
    keywords: ["status", "pipeline", "stage"],
    tier: "simple",
    valueKind: "leadStatus",
  }),
  c({
    id: "priority",
    label: "Priorität ist",
    description: "Nur bei einer bestimmten Priorität (HOT/WARM/COLD).",
    category: "Lead-Eigenschaften",
    icon: "flag",
    tone: "amber",
    keywords: ["priorität", "priority", "hot", "warm", "cold"],
    tier: "pro",
    valueKind: "priority",
  }),
  c({
    id: "scoreGreaterThan",
    label: "Score größer als",
    description: "Nur wenn der Lead-Score über einem Wert liegt.",
    category: "Lead-Eigenschaften",
    icon: "gauge",
    tone: "violet",
    keywords: ["score", "punkte", "bewertung", "größer"],
    tier: "pro",
    valueKind: "number",
  }),
  c({
    id: "funnelStage",
    label: "Funnel-Phase ist",
    description: "Nur in einer bestimmten Funnel-Phase.",
    category: "Lead-Eigenschaften",
    icon: "funnel",
    tone: "blue",
    keywords: ["funnel", "phase", "stage"],
    tier: "pro",
    valueKind: "text",
  }),
  c({
    id: "ownerAssigned",
    label: "Bearbeiter zugewiesen",
    description: "Nur wenn dem Lead ein Bearbeiter zugewiesen ist.",
    category: "Lead-Eigenschaften",
    icon: "user",
    tone: "blue",
    keywords: ["bearbeiter", "owner", "zugewiesen"],
    tier: "simple",
  }),
  c({
    id: "hasWhatsappConsent",
    label: "WhatsApp-Einwilligung vorhanden",
    description: "Nur wenn eine WhatsApp-Einwilligung vorliegt.",
    category: "Kommunikation",
    icon: "chat",
    tone: "emerald",
    keywords: ["whatsapp", "consent", "einwilligung", "opt-in"],
    tier: "simple",
  }),
  c({
    id: "hasEmailConsent",
    label: "E-Mail-Einwilligung vorhanden",
    description: "Nur wenn eine E-Mail-Einwilligung vorliegt.",
    category: "Kommunikation",
    icon: "mail",
    tone: "indigo",
    keywords: ["email", "consent", "einwilligung", "opt-in"],
    tier: "simple",
  }),
  c({
    id: "missingDocuments",
    label: "Dokumente fehlen",
    description: "Nur wenn noch Unterlagen fehlen.",
    category: "Dokumente",
    icon: "docMissing",
    tone: "teal",
    keywords: ["dokumente", "unterlagen", "fehlen", "missing"],
    tier: "pro",
  }),
  c({
    id: "noInboundReplyForHours",
    label: "Keine Antwort seit … Stunden",
    description: "Nur wenn der Lead seit X Stunden nicht geantwortet hat.",
    category: "Zeit",
    icon: "clock",
    tone: "amber",
    keywords: ["keine antwort", "stille", "reply", "stunden"],
    tier: "pro",
    valueKind: "hours",
  }),
  c({
    id: "noFormOpenedForHours",
    label: "Formular nicht geöffnet seit … Stunden",
    description: "Nur wenn das Formular seit X Stunden nicht geöffnet wurde.",
    category: "Zeit",
    icon: "clock",
    tone: "amber",
    keywords: ["formular", "eignungscheck", "geöffnet", "stunden"],
    tier: "pro",
    valueKind: "hours",
  }),
  c({
    id: "noUploadForHours",
    label: "Kein Upload seit … Stunden",
    description: "Nur wenn seit X Stunden kein Dokument hochgeladen wurde.",
    category: "Zeit",
    icon: "clock",
    tone: "amber",
    keywords: ["upload", "dokument", "stunden"],
    tier: "pro",
    valueKind: "hours",
  }),
  c({
    id: "businessHoursOnly",
    label: "Nur innerhalb der Geschäftszeiten",
    description: "Nur Mo–Fr zwischen 08:00 und 18:00 Uhr.",
    category: "Zeit",
    icon: "clock",
    tone: "slate",
    keywords: ["geschäftszeiten", "business hours", "arbeitszeit"],
    tier: "pro",
  }),
  c({
    id: "isDemo",
    label: "Ist Demo-Lead",
    description: "Nur für Demo-Datensätze (Test/Schulung).",
    category: "System",
    icon: "bolt",
    tone: "slate",
    keywords: ["demo", "test"],
    tier: "enterprise",
  }),
];

const actions: CatalogEntry[] = [
  // Kommunikation
  a({
    id: "sendTemplateSimulation",
    label: "Nachricht senden",
    description: "Sendet eine WhatsApp-/E-Mail-Vorlage an den Lead.",
    category: "Kommunikation",
    icon: "mail",
    tone: "emerald",
    keywords: ["nachricht", "whatsapp", "email", "vorlage", "senden"],
    tier: "simple",
    configKind: "template",
  }),
  a({
    id: "notifyAdminSimulation",
    label: "Team benachrichtigen",
    description: "Informiert das Team/den Admin (interne Notiz).",
    category: "Kommunikation",
    icon: "note",
    tone: "amber",
    keywords: ["benachrichtigen", "admin", "team", "hinweis"],
    tier: "pro",
    configKind: "note",
  }),
  // CRM
  a({
    id: "changeLeadStatus",
    label: "Status ändern",
    description: "Setzt den Lead auf einen neuen Pipeline-Status.",
    category: "CRM",
    icon: "swap",
    tone: "blue",
    keywords: ["status", "pipeline", "stage", "ändern"],
    tier: "simple",
    configKind: "status",
  }),
  a({
    id: "assignOwner",
    label: "Bearbeiter zuweisen",
    description: "Weist den Lead einem Bearbeiter zu.",
    category: "CRM",
    icon: "userPlus",
    tone: "blue",
    keywords: ["bearbeiter", "owner", "zuweisen", "assign"],
    tier: "pro",
    configKind: "owner",
  }),
  a({
    id: "markEscalated",
    label: "Als HOT markieren",
    description: "Eskaliert den Lead (Priorität HOT).",
    category: "CRM",
    icon: "flag",
    tone: "rose",
    keywords: ["eskalation", "hot", "priorität", "wichtig"],
    tier: "pro",
    configKind: "none",
  }),
  a({
    id: "addActivityLog",
    label: "Aktivität protokollieren",
    description: "Schreibt einen Eintrag ins Aktivitätsprotokoll.",
    category: "CRM",
    icon: "note",
    tone: "slate",
    keywords: ["protokoll", "log", "aktivität", "notiz"],
    tier: "pro",
    configKind: "note",
  }),
  // Aufgabe
  a({
    id: "createTask",
    label: "Aufgabe erstellen",
    description: "Legt eine Aufgabe für das Team an.",
    category: "Aufgabe",
    icon: "task",
    tone: "violet",
    keywords: ["aufgabe", "task", "todo", "erstellen"],
    tier: "simple",
    configKind: "taskTitle",
  }),
  a({
    id: "createFollowUp",
    label: "Wiedervorlage setzen",
    description: "Plant eine Wiedervorlage in X Stunden.",
    category: "Aufgabe",
    icon: "clock",
    tone: "violet",
    keywords: ["wiedervorlage", "follow up", "reminder", "erinnerung"],
    tier: "pro",
    configKind: "hours",
  }),
  // Roadmap connectors (Enterprise, disabled)
  a({
    id: "roadmap.sms",
    label: "SMS senden",
    description: "Sendet eine SMS an den Lead.",
    category: "Kommunikation",
    icon: "sms",
    tone: "sky",
    keywords: ["sms", "textnachricht"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.push",
    label: "Push senden",
    description: "Sendet eine Push-Benachrichtigung.",
    category: "Kommunikation",
    icon: "push",
    tone: "sky",
    keywords: ["push", "benachrichtigung"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.webhook",
    label: "Webhook",
    description: "Ruft einen Webhook eines Drittsystems auf.",
    category: "Automatisierung",
    icon: "webhook",
    tone: "fuchsia",
    keywords: ["webhook", "callback", "http"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.http",
    label: "HTTP Request",
    description: "Führt einen beliebigen HTTP-Request aus.",
    category: "Automatisierung",
    icon: "http",
    tone: "fuchsia",
    keywords: ["http", "rest", "api", "request"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.ai",
    label: "KI-Prompt",
    description: "Lässt eine KI Text erzeugen oder klassifizieren.",
    category: "Automatisierung",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["ki", "ai", "gpt", "prompt", "llm"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.slack",
    label: "Slack",
    description: "Sendet eine Nachricht in einen Slack-Channel.",
    category: "Externe Systeme",
    icon: "slack",
    tone: "fuchsia",
    keywords: ["slack", "channel", "team"],
    tier: "enterprise",
    comingSoon: true,
  }),
];

export const leadsPlugin: WorkflowPlugin = {
  id: "leads",
  label: "Leads & CRM",
  triggers,
  conditions,
  actions,
};
