/**
 * Leads workflow plugin.
 *
 * Contributes the lead/CRM triggers, conditions and actions to the generic
 * registry. Every real entry's `id` matches the existing AutomationRule
 * vocabulary (AutomationTrigger / RuleConditionType / RuleActionType) so the
 * persisted rule JSON is unchanged.
 *
 * `comingSoon` entries are roadmap connectors: shown (in Enterprise mode) but
 * disabled and never persistable — purely to make the catalog's breadth and
 * the plugin architecture visible.
 */
import type { CatalogEntry, WorkflowPlugin } from "./registry";

const t = (e: Omit<CatalogEntry, "kind" | "plugin">): CatalogEntry => ({
  ...e,
  kind: "trigger",
  plugin: "leads",
});
const c = (e: Omit<CatalogEntry, "kind" | "plugin">): CatalogEntry => ({
  ...e,
  kind: "condition",
  plugin: "leads",
});
const a = (e: Omit<CatalogEntry, "kind" | "plugin">): CatalogEntry => ({
  ...e,
  kind: "action",
  plugin: "leads",
});

const triggers: CatalogEntry[] = [
  // Leads
  t({
    id: "LEAD_CREATED",
    label: "Lead erstellt",
    description: "Startet, sobald ein neuer Lead angelegt wird.",
    category: "Leads",
    icon: "userPlus",
    tone: "indigo",
    keywords: ["neu", "new", "anlegen", "eingang"],
    tier: "simple",
  }),
  t({
    id: "MANUAL",
    label: "Manuell / Test",
    description: "Wird nur manuell ausgelöst – ideal zum Testen.",
    category: "Leads",
    icon: "bolt",
    tone: "slate",
    keywords: ["test", "manuell", "hand"],
    tier: "simple",
  }),
  // Kommunikation
  t({
    id: "MESSAGE_INBOUND",
    label: "Antwort erhalten",
    description: "Der Lead hat auf WhatsApp oder E-Mail geantwortet.",
    category: "Kommunikation",
    icon: "reply",
    tone: "emerald",
    keywords: ["antwort", "reply", "inbound", "whatsapp", "eingehend"],
    tier: "simple",
  }),
  t({
    id: "MESSAGE_FAILED",
    label: "Nachricht fehlgeschlagen",
    description: "Eine ausgehende Nachricht konnte nicht zugestellt werden.",
    category: "Kommunikation",
    icon: "x",
    tone: "rose",
    keywords: ["fehler", "failed", "bounce", "zustellung"],
    tier: "pro",
  }),
  // Termine
  t({
    id: "APPOINTMENT_CREATED",
    label: "Termin erstellt",
    description: "Ein Termin wurde für den Lead angelegt.",
    category: "Termine",
    icon: "calendar",
    tone: "sky",
    keywords: ["termin", "appointment", "meeting", "kalender"],
    tier: "simple",
  }),
  t({
    id: "APPOINTMENT_MISSED",
    label: "Termin verpasst",
    description: "Der Lead ist nicht zum Termin erschienen (No-Show).",
    category: "Termine",
    icon: "calendarX",
    tone: "rose",
    keywords: ["no show", "verpasst", "missed", "nicht erschienen"],
    tier: "pro",
  }),
  // Dokumente
  t({
    id: "DOCUMENT_REQUESTED",
    label: "Dokument angefordert",
    description: "Es wurde ein Dokument vom Lead angefordert.",
    category: "Dokumente",
    icon: "doc",
    tone: "teal",
    keywords: ["dokument", "unterlagen", "angefordert", "request"],
    tier: "pro",
  }),
  t({
    id: "DOCUMENT_UPLOADED",
    label: "Dokument hochgeladen",
    description: "Der Lead hat ein Dokument hochgeladen.",
    category: "Dokumente",
    icon: "doc",
    tone: "teal",
    keywords: ["upload", "hochgeladen", "dokument"],
    tier: "simple",
  }),
  t({
    id: "DOCUMENT_APPROVED",
    label: "Dokument geprüft",
    description: "Ein hochgeladenes Dokument wurde geprüft/freigegeben.",
    category: "Dokumente",
    icon: "docCheck",
    tone: "teal",
    keywords: ["geprüft", "approved", "freigegeben", "dokument"],
    tier: "pro",
  }),
  // Funnel / Eignungscheck
  t({
    id: "FUNNEL_STARTED",
    label: "Funnel gestartet",
    description:
      "Löst aus, sobald der Lead den Eignungscheck / Funnel startet.",
    category: "Funnel",
    icon: "bolt",
    tone: "violet",
    keywords: ["funnel", "eignungscheck", "gestartet", "start", "begonnen"],
    tier: "simple",
  }),
  t({
    id: "FUNNEL_COMPLETED",
    label: "Funnel abgeschlossen",
    description:
      "Löst aus, sobald der Lead den Eignungscheck / Funnel abschließt.",
    category: "Funnel",
    icon: "docCheck",
    tone: "violet",
    keywords: ["funnel", "eignungscheck", "abgeschlossen", "fertig", "complete"],
    tier: "simple",
  }),
  // Vertrieb
  t({
    id: "LEAD_STATUS_CHANGED",
    label: "Status geändert",
    description: "Der Pipeline-Status des Leads hat sich geändert.",
    category: "Vertrieb",
    icon: "swap",
    tone: "blue",
    keywords: ["status", "pipeline", "stage", "phase"],
    tier: "simple",
  }),
  t({
    id: "LEAD_OWNER_ASSIGNED",
    label: "Bearbeiter geändert",
    description: "Dem Lead wurde ein (neuer) Bearbeiter zugewiesen.",
    category: "Vertrieb",
    icon: "userPlus",
    tone: "blue",
    keywords: ["bearbeiter", "owner", "zuweisung", "assignee"],
    tier: "pro",
  }),
  t({
    id: "TASK_OVERDUE",
    label: "Aufgabe überfällig",
    description: "Eine Aufgabe zum Lead ist überfällig.",
    category: "Vertrieb",
    icon: "clock",
    tone: "amber",
    keywords: ["aufgabe", "task", "überfällig", "overdue"],
    tier: "pro",
  }),
  t({
    id: "SLA_EXCEEDED",
    label: "SLA überschritten",
    description: "Eine Reaktionszeit-Vorgabe (SLA) wurde überschritten.",
    category: "Vertrieb",
    icon: "gauge",
    tone: "amber",
    keywords: ["sla", "reaktionszeit", "frist", "eskalation"],
    tier: "enterprise",
  }),
  // Roadmap connectors (visible in Enterprise, disabled)
  t({
    id: "roadmap.wa_delivered",
    label: "WhatsApp zugestellt",
    description: "Löst aus, sobald eine WhatsApp zugestellt wurde.",
    category: "Kommunikation",
    icon: "check2",
    tone: "emerald",
    keywords: ["whatsapp", "zugestellt", "delivered"],
    tier: "enterprise",
    comingSoon: true,
  }),
  t({
    id: "roadmap.wa_read",
    label: "WhatsApp gelesen",
    description: "Löst aus, sobald eine WhatsApp gelesen wurde.",
    category: "Kommunikation",
    icon: "check2",
    tone: "emerald",
    keywords: ["whatsapp", "gelesen", "read", "blaue haken"],
    tier: "enterprise",
    comingSoon: true,
  }),
  t({
    id: "roadmap.link_clicked",
    label: "Link geklickt",
    description: "Löst aus, sobald der Lead einen Link geklickt hat.",
    category: "Kommunikation",
    icon: "link",
    tone: "emerald",
    keywords: ["link", "klick", "click", "tracking"],
    tier: "enterprise",
    comingSoon: true,
  }),
];

const conditions: CatalogEntry[] = [
  c({
    id: "leadStatus",
    label: "Status ist",
    description: "Nur wenn der Lead einen bestimmten Status hat.",
    category: "Lead-Eigenschaften",
    icon: "swap",
    tone: "blue",
    keywords: ["status", "pipeline", "stage"],
    tier: "simple",
    valueKind: "leadStatus",
  }),
  c({
    id: "priority",
    label: "Priorität ist",
    description: "Nur bei einer bestimmten Priorität (HOT/WARM/COLD).",
    category: "Lead-Eigenschaften",
    icon: "flag",
    tone: "amber",
    keywords: ["priorität", "priority", "hot", "warm", "cold"],
    tier: "pro",
    valueKind: "priority",
  }),
  c({
    id: "scoreGreaterThan",
    label: "Score größer als",
    description: "Nur wenn der Lead-Score über einem Wert liegt.",
    category: "Lead-Eigenschaften",
    icon: "gauge",
    tone: "violet",
    keywords: ["score", "punkte", "bewertung", "größer"],
    tier: "pro",
    valueKind: "number",
  }),
  c({
    id: "funnelPhase",
    label: "Funnel-Phase ist",
    description:
      "Nur in einer bestimmten Prozess-Phase (getrennt vom Kommunikations-Status).",
    category: "Lead-Eigenschaften",
    icon: "funnel",
    tone: "blue",
    keywords: ["funnel", "phase", "prozess", "stage", "eignungscheck", "unterlagen"],
    tier: "pro",
    valueKind: "funnelPhase",
  }),
  c({
    id: "ownerAssigned",
    label: "Bearbeiter zugewiesen",
    description: "Nur wenn dem Lead ein Bearbeiter zugewiesen ist.",
    category: "Lead-Eigenschaften",
    icon: "user",
    tone: "blue",
    keywords: ["bearbeiter", "owner", "zugewiesen"],
    tier: "simple",
  }),
  c({
    id: "hasWhatsappConsent",
    label: "WhatsApp-Einwilligung vorhanden",
    description: "Nur wenn eine WhatsApp-Einwilligung vorliegt.",
    category: "Kommunikation",
    icon: "chat",
    tone: "emerald",
    keywords: ["whatsapp", "consent", "einwilligung", "opt-in"],
    tier: "simple",
  }),
  c({
    id: "hasEmailConsent",
    label: "E-Mail-Einwilligung vorhanden",
    description: "Nur wenn eine E-Mail-Einwilligung vorliegt.",
    category: "Kommunikation",
    icon: "mail",
    tone: "indigo",
    keywords: ["email", "consent", "einwilligung", "opt-in"],
    tier: "simple",
  }),
  // Eingehende Antwort (nur sinnvoll mit Trigger „Antwort erhalten")
  c({
    id: "whatsappReplyReceived",
    label: "WhatsApp-Antwort erhalten",
    description: "Nur wenn der Lead per WhatsApp geantwortet hat.",
    category: "Antwort des Leads",
    icon: "reply",
    tone: "emerald",
    keywords: ["antwort", "reply", "eingegangen", "geantwortet", "whatsapp"],
    tier: "simple",
  }),
  c({
    id: "quickReplySelection",
    label: "Quick-Reply-Auswahl ist",
    description:
      "Nur wenn der Lead einen bestimmten Antwort-Button gewählt hat (Beschäftigt / Arbeitssuchend / Sonstige).",
    category: "Antwort des Leads",
    icon: "chat",
    tone: "emerald",
    keywords: ["quick reply", "button", "auswahl", "beschäftigt", "arbeitssuchend"],
    tier: "simple",
    valueKind: "situation",
  }),
  c({
    id: "detectedSituation",
    label: "Erkannte berufliche Situation",
    description:
      "Nur wenn aus Button ODER Freitext die berufliche Situation erkannt wurde.",
    category: "Antwort des Leads",
    icon: "user",
    tone: "emerald",
    keywords: ["situation", "beschäftigt", "arbeitssuchend", "sonstige", "erkannt"],
    tier: "simple",
    valueKind: "situation",
  }),
  c({
    id: "replyTextContains",
    label: "Antworttext enthält",
    description: "Nur wenn die Antwort ein bestimmtes Stichwort enthält.",
    category: "Antwort des Leads",
    icon: "chat",
    tone: "emerald",
    keywords: ["text", "enthält", "stichwort", "freitext", "contains"],
    tier: "pro",
    valueKind: "text",
  }),
  c({
    id: "replyTextEquals",
    label: "Antworttext entspricht",
    description: "Nur wenn die Antwort exakt einem Text entspricht.",
    category: "Antwort des Leads",
    icon: "chat",
    tone: "emerald",
    keywords: ["text", "entspricht", "exakt", "freitext", "equals"],
    tier: "pro",
    valueKind: "text",
  }),
  // KI-Antwortanalyse — versteht Quick-Replys UND Freitext. Die KI klassifiziert
  // nur, sie generiert nie Nachrichten. Alle Flags sind per UND/ODER kombinierbar.
  c({
    id: "analyzeReply",
    label: "Antwort analysieren (KI)",
    description:
      "Analysiert die eingehende Nachricht (Button ODER Freitext). Trifft zu, wenn die Zuordnung sicher genug ist – sonst manuelle Prüfung.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["ki", "ai", "analyse", "freitext", "verstehen", "klassifizieren"],
    tier: "simple",
  }),
  c({
    id: "aiInterestDetected",
    label: "Interesse erkannt",
    description: "Die KI hat aus der Antwort Interesse erkannt.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["interesse", "ja", "interessiert"],
    tier: "simple",
  }),
  c({
    id: "aiEmployed",
    label: "Beschäftigt erkannt",
    description: "Die KI hat erkannt, dass der Lead beschäftigt ist.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["beschäftigt", "angestellt", "job"],
    tier: "simple",
  }),
  c({
    id: "aiJobSeeking",
    label: "Arbeitssuchend erkannt",
    description: "Die KI hat erkannt, dass der Lead arbeitssuchend ist.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["arbeitssuchend", "arbeitslos", "jobsuche"],
    tier: "simple",
  }),
  c({
    id: "aiCareerChange",
    label: "Berufliche Veränderung erkannt",
    description: "Die KI hat einen Wunsch nach beruflicher Veränderung erkannt.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["veränderung", "wechsel", "umorientierung", "quereinstieg"],
    tier: "pro",
  }),
  c({
    id: "aiJobInsecure",
    label: "Arbeitsplatz unsicher erkannt",
    description: "Die KI hat einen unsicheren Arbeitsplatz erkannt.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["unsicher", "kündigung", "befristet", "kurzarbeit"],
    tier: "pro",
  }),
  c({
    id: "aiGeneralInterest",
    label: "Allgemeines Interesse erkannt",
    description: "Interesse ohne konkrete berufliche Situation.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["allgemein", "interesse", "mehr infos"],
    tier: "pro",
  }),
  c({
    id: "aiCallback",
    label: "Rückruf erkannt",
    description: "Der Lead möchte zurückgerufen werden.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["rückruf", "anrufen", "telefon"],
    tier: "simple",
  }),
  c({
    id: "aiQuestion",
    label: "Frage erkannt",
    description: "Der Lead hat eine Frage gestellt.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["frage", "wie", "was", "gehalt", "voraussetzung"],
    tier: "pro",
  }),
  c({
    id: "aiStop",
    label: "STOPP erkannt",
    description: "Der Lead möchte keine weiteren Nachrichten (Opt-out).",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "rose",
    keywords: ["stopp", "stop", "abmelden", "opt-out"],
    tier: "simple",
  }),
  c({
    id: "aiNoInterest",
    label: "Kein Interesse erkannt",
    description: "Die KI hat fehlendes Interesse erkannt.",
    category: "KI-Antwortanalyse",
    icon: "ai",
    tone: "rose",
    keywords: ["kein interesse", "passt nicht", "nein"],
    tier: "simple",
  }),
  c({
    id: "missingDocuments",
    label: "Dokumente fehlen",
    description: "Nur wenn noch Unterlagen fehlen.",
    category: "Dokumente",
    icon: "docMissing",
    tone: "teal",
    keywords: ["dokumente", "unterlagen", "fehlen", "missing"],
    tier: "pro",
  }),
  c({
    id: "noInboundReplyForHours",
    label: "Keine Antwort seit … Stunden",
    description: "Nur wenn der Lead seit X Stunden nicht geantwortet hat.",
    category: "Zeit",
    icon: "clock",
    tone: "amber",
    keywords: ["keine antwort", "stille", "reply", "stunden"],
    tier: "pro",
    valueKind: "hours",
  }),
  c({
    id: "noFormOpenedForHours",
    label: "Formular nicht geöffnet seit … Stunden",
    description: "Nur wenn das Formular seit X Stunden nicht geöffnet wurde.",
    category: "Zeit",
    icon: "clock",
    tone: "amber",
    keywords: ["formular", "eignungscheck", "geöffnet", "stunden"],
    tier: "pro",
    valueKind: "hours",
  }),
  c({
    id: "noUploadForHours",
    label: "Kein Upload seit … Stunden",
    description: "Nur wenn seit X Stunden kein Dokument hochgeladen wurde.",
    category: "Zeit",
    icon: "clock",
    tone: "amber",
    keywords: ["upload", "dokument", "stunden"],
    tier: "pro",
    valueKind: "hours",
  }),
  c({
    id: "businessHoursOnly",
    label: "Nur innerhalb der Geschäftszeiten",
    description: "Nur Mo–Fr zwischen 08:00 und 18:00 Uhr.",
    category: "Zeit",
    icon: "clock",
    tone: "slate",
    keywords: ["geschäftszeiten", "business hours", "arbeitszeit"],
    tier: "pro",
  }),
  c({
    id: "isDemo",
    label: "Ist Demo-Lead",
    description: "Nur für Demo-Datensätze (Test/Schulung).",
    category: "System",
    icon: "bolt",
    tone: "slate",
    keywords: ["demo", "test"],
    tier: "enterprise",
  }),
];

const actions: CatalogEntry[] = [
  // Kommunikation
  a({
    id: "sendTemplateSimulation",
    label: "Nachricht senden",
    description: "Sendet eine WhatsApp-/E-Mail-Vorlage an den Lead.",
    category: "Kommunikation",
    icon: "mail",
    tone: "emerald",
    keywords: ["nachricht", "whatsapp", "email", "vorlage", "senden"],
    tier: "simple",
    configKind: "template",
  }),
  a({
    id: "notifyAdminSimulation",
    label: "Team benachrichtigen",
    description: "Informiert das Team/den Admin (interne Notiz).",
    category: "Kommunikation",
    icon: "note",
    tone: "amber",
    keywords: ["benachrichtigen", "admin", "team", "hinweis"],
    tier: "pro",
    configKind: "note",
  }),
  // CRM
  a({
    id: "changeLeadStatus",
    label: "Status ändern",
    description: "Setzt den Lead auf einen neuen Pipeline-Status.",
    category: "CRM",
    icon: "swap",
    tone: "blue",
    keywords: ["status", "pipeline", "stage", "ändern"],
    tier: "simple",
    configKind: "status",
  }),
  a({
    id: "assignOwner",
    label: "Bearbeiter zuweisen",
    description: "Weist den Lead einem Bearbeiter zu.",
    category: "CRM",
    icon: "userPlus",
    tone: "blue",
    keywords: ["bearbeiter", "owner", "zuweisen", "assign"],
    tier: "pro",
    configKind: "owner",
  }),
  a({
    id: "changeFunnelPhase",
    label: "Funnel-Phase ändern",
    description: "Setzt die Prozess-Phase (getrennt vom Kommunikations-Status).",
    category: "CRM",
    icon: "funnel",
    tone: "blue",
    keywords: ["funnel", "phase", "prozess", "eignungscheck", "unterlagen", "termin"],
    tier: "simple",
    configKind: "funnelPhase",
  }),
  a({
    id: "addTag",
    label: "Tag hinzufügen",
    description: "Fügt dem Lead ein Tag hinzu.",
    category: "CRM",
    icon: "flag",
    tone: "teal",
    keywords: ["tag", "label", "markierung", "hinzufügen"],
    tier: "simple",
    configKind: "tag",
  }),
  a({
    id: "removeTag",
    label: "Tag entfernen",
    description: "Entfernt ein Tag vom Lead.",
    category: "CRM",
    icon: "flag",
    tone: "slate",
    keywords: ["tag", "label", "markierung", "entfernen"],
    tier: "pro",
    configKind: "tag",
  }),
  a({
    id: "changeScore",
    label: "Lead-Score ändern",
    description: "Erhöht oder senkt den Lead-Score (z. B. +10 / -5).",
    category: "CRM",
    icon: "gauge",
    tone: "violet",
    keywords: ["score", "punkte", "bewertung", "ändern"],
    tier: "pro",
    configKind: "score",
  }),
  a({
    id: "pauseAutomation",
    label: "Automation pausieren",
    description: "Pausiert alle weiteren Automationen für diesen Lead.",
    category: "CRM",
    icon: "clock",
    tone: "amber",
    keywords: ["pausieren", "stop", "anhalten", "automation"],
    tier: "pro",
    configKind: "none",
  }),
  a({
    id: "resumeAutomation",
    label: "Automation fortsetzen",
    description: "Setzt pausierte Automationen wieder fort.",
    category: "CRM",
    icon: "bolt",
    tone: "emerald",
    keywords: ["fortsetzen", "resume", "weiter", "automation"],
    tier: "pro",
    configKind: "none",
  }),
  a({
    id: "addNote",
    label: "Notiz zur Timeline hinzufügen",
    description: "Schreibt eine Notiz in die Lead-Timeline.",
    category: "CRM",
    icon: "note",
    tone: "slate",
    keywords: ["notiz", "note", "timeline", "kommentar"],
    tier: "simple",
    configKind: "note",
  }),
  a({
    id: "notifyInternal",
    label: "Interne Benachrichtigung",
    description: "Benachrichtigt das Team (Aufgabe für den Bearbeiter).",
    category: "CRM",
    icon: "push",
    tone: "amber",
    keywords: ["benachrichtigung", "intern", "team", "hinweis"],
    tier: "pro",
    configKind: "note",
  }),
  a({
    id: "markEscalated",
    label: "Als HOT markieren",
    description: "Eskaliert den Lead (Priorität HOT).",
    category: "CRM",
    icon: "flag",
    tone: "rose",
    keywords: ["eskalation", "hot", "priorität", "wichtig"],
    tier: "pro",
    configKind: "none",
  }),
  a({
    id: "addActivityLog",
    label: "Aktivität protokollieren",
    description: "Schreibt einen Eintrag ins Aktivitätsprotokoll.",
    category: "CRM",
    icon: "note",
    tone: "slate",
    keywords: ["protokoll", "log", "aktivität", "notiz"],
    tier: "pro",
    configKind: "note",
  }),
  // Aufgabe
  a({
    id: "createTask",
    label: "Aufgabe erstellen",
    description: "Legt eine Aufgabe für das Team an.",
    category: "Aufgabe",
    icon: "task",
    tone: "violet",
    keywords: ["aufgabe", "task", "todo", "erstellen"],
    tier: "simple",
    configKind: "taskTitle",
  }),
  a({
    id: "createFollowUp",
    label: "Wiedervorlage setzen",
    description: "Plant eine Wiedervorlage in X Stunden.",
    category: "Aufgabe",
    icon: "clock",
    tone: "violet",
    keywords: ["wiedervorlage", "follow up", "reminder", "erinnerung"],
    tier: "pro",
    configKind: "hours",
  }),
  // Ablaufsteuerung
  a({
    id: "delay",
    label: "Warten (Delay)",
    description: "Wartet eine definierte Zeit (Minuten / Stunden / Tage).",
    category: "Ablauf",
    icon: "clock",
    tone: "slate",
    keywords: ["warten", "delay", "verzögerung", "pause", "zeit"],
    tier: "simple",
    configKind: "delay",
  }),
  a({
    id: "branch",
    label: "Verzweigung (Wenn/Sonst)",
    description:
      "Führt die folgenden Schritte nur aus, wenn die Bedingung erfüllt ist – sonst endet der Workflow.",
    category: "Ablauf",
    icon: "swap",
    tone: "amber",
    keywords: ["verzweigung", "if", "else", "wenn", "sonst", "branch"],
    tier: "pro",
    configKind: "branch",
  }),
  a({
    id: "endWorkflow",
    label: "Workflow beenden",
    description: "Beendet den Workflow – nachfolgende Schritte werden übersprungen.",
    category: "Ablauf",
    icon: "x",
    tone: "rose",
    keywords: ["beenden", "ende", "stop", "abbrechen", "workflow"],
    tier: "simple",
    configKind: "none",
  }),
  // Roadmap connectors (Enterprise, disabled)
  a({
    id: "roadmap.sms",
    label: "SMS senden",
    description: "Sendet eine SMS an den Lead.",
    category: "Kommunikation",
    icon: "sms",
    tone: "sky",
    keywords: ["sms", "textnachricht"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.push",
    label: "Push senden",
    description: "Sendet eine Push-Benachrichtigung.",
    category: "Kommunikation",
    icon: "push",
    tone: "sky",
    keywords: ["push", "benachrichtigung"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.webhook",
    label: "Webhook",
    description: "Ruft einen Webhook eines Drittsystems auf.",
    category: "Automatisierung",
    icon: "webhook",
    tone: "fuchsia",
    keywords: ["webhook", "callback", "http"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.http",
    label: "HTTP Request",
    description: "Führt einen beliebigen HTTP-Request aus.",
    category: "Automatisierung",
    icon: "http",
    tone: "fuchsia",
    keywords: ["http", "rest", "api", "request"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.ai",
    label: "KI-Prompt",
    description: "Lässt eine KI Text erzeugen oder klassifizieren.",
    category: "Automatisierung",
    icon: "ai",
    tone: "fuchsia",
    keywords: ["ki", "ai", "gpt", "prompt", "llm"],
    tier: "enterprise",
    comingSoon: true,
  }),
  a({
    id: "roadmap.slack",
    label: "Slack",
    description: "Sendet eine Nachricht in einen Slack-Channel.",
    category: "Externe Systeme",
    icon: "slack",
    tone: "fuchsia",
    keywords: ["slack", "channel", "team"],
    tier: "enterprise",
    comingSoon: true,
  }),
];

export const leadsPlugin: WorkflowPlugin = {
  id: "leads",
  label: "Leads & CRM",
  triggers,
  conditions,
  actions,
};
